/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * NewJFrame.java
 *
 * Created on 24 Μαϊ 2010, 1:44:07 μμ
 */
package jnodes3clientse;

//import dataGenerator.snmpGetIfList;
import java.awt.Container;
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import message.*;
import org.apache.commons.cli.*;
import org.apache.commons.cli.help.HelpFormatter;

/**
 *
 * @author Administrator
 */
public class Main extends javax.swing.JFrame {

    public static MapViewer gp = new MapViewer();
    public static MapManager sp = new MapManager();
    private static Container contentPane;
    public static boolean authedAdmin = true, windowActive = false;
    public static String encryption_password = null;

    /**
     * Creates new form NewJFrame
     */
    public Main() {

        //snmpGetIfList a = new snmpGetIfList("41.128.32.57", "snmpnagios", "3nkIX5E9TyM4txev", "jwRmJzG2Nu7QkPk0");
        //for(String s : a.getList())
        //System.out.println(s);
        //System.out.println(a.getList().length);
        //System.exit(0);
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(Main.class.getClassLoader().getResource("jnodes.png")));

        dataManagement.storage.addMapFromFile();

        setSize(600, 350);
        setTitle("JnodesOne version 1.2");
        contentPane = getContentPane();
        switch2mapview();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public static void switch2maplist() {
        contentPane.removeAll();
        contentPane.add(sp);
        contentPane.invalidate();
        contentPane.validate();
        contentPane.repaint();
    }

    public static void switch2mapview() {
        contentPane.removeAll();
        contentPane.add(gp);
        contentPane.invalidate();
        contentPane.validate();
        contentPane.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }

            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        windowActive = true;
    }//GEN-LAST:event_formWindowActivated

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
        windowActive = false;
    }//GEN-LAST:event_formWindowDeactivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // auto load encryption key from file if exists (standalone exe friendly)
        try {
            java.nio.file.Path p = java.nio.file.Paths.get("encryption.key");
            if (java.nio.file.Files.exists(p)) {
                encryption_password = java.nio.file.Files.readString(p).trim();
                System.out.println("Encryption key loaded from encryption.key file");
            }
        } catch (Exception ex) {
            System.err.println("Failed reading encryption.key file: " + ex.getMessage());
        }

        // Create a new Options object
        Options options = new Options();

        // Add options
        options.addOption("h", "help", false, "Display help information");
        options.addOption("k", "key", true, "The encryption key to use");

        // Get a parser
        CommandLineParser parser = new DefaultParser();
        CommandLine cmd;

        try {
            // Parse the command line arguments
            cmd = parser.parse(options, args);
        } catch (ParseException e) {
            System.err.println("Error parsing arguments: " + e.getMessage());
            // Display help on parse error
            HelpFormatter fmt = HelpFormatter.builder().get();
            try {
                fmt.printHelp("jnodesOne", null, options, null, true);
            } catch (IOException ex) {
                ex.printStackTrace(); // or System.err.println("help print failed");
            }
            return;
        }

        java.awt.EventQueue.invokeLater(() -> {
            if (cmd.hasOption("k")) {
                encryption_password = cmd.getOptionValue("k");
                System.out.println("key: " + encryption_password);
            }

            if (encryption_password == null || encryption_password.isEmpty()) {
                //System.out.println("**WARNING** No encryption key provided, passwords in map file will be stored unencrypted!");
                //tools.ModalMsg.display("<html> **WARNING** No encryption key provided, <br>passwords in map file will be stored unencrypted! </html>");
                EncryptionPrompt ep = new EncryptionPrompt();
                Object[] options1 = {"Ok", "Cancel"};
                JOptionPane op = new JOptionPane(
                        ep,
                        JOptionPane.PLAIN_MESSAGE,
                        JOptionPane.OK_CANCEL_OPTION,
                        null,
                        options1);

                JDialog dialog = op.createDialog(null, "Encryption");
                dialog.setVisible(true);
                Object selectedValue = op.getValue();

                if (selectedValue != null && selectedValue.equals("Ok") && ep.getSelection() != null && !ep.getSelection().isEmpty()) {
                    encryption_password = ep.getSelection();
                    if (ep.createFile.isSelected()) {
                        //create the file
                        try {
                            java.nio.file.Path keyFile = java.nio.file.Paths.get("encryption.key");
                            java.nio.file.Files.writeString(keyFile, encryption_password + System.lineSeparator());
                            System.out.println("encryption.key file created.");
                        } catch (Exception ex) {
                            System.err.println("Failed to create encryption.key file: " + ex.getMessage());
                        }
                    }
                } else {
                    tools.ModalMsg.display("<html> **WARNING** No encryption key provided, <br>passwords in map file will be stored unencrypted! </html>");
                }
            }

            new Main().setVisible(true);
        });
    }

    public static void updateMapMonitor(mapData mapData) {
        gp.updateMainAnim(mapData);
    }

    public static void updateMapList(mapData mapListData) {
        MapManager.jTable1.setModel(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
