/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminPanel.java
 *
 * Created on 4 Ιουλ 2010, 12:42:11 μμ
 */
package jnodes3clientse;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usah
 */
public class MapManager extends javax.swing.JPanel {

    DefaultTableModel a;

    /** Creates new form AdminPanel */
    public MapManager() {
        initComponents();
        a = new DefaultTableModel();
        jTable1.setModel(a);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        gotoMapButton = new javax.swing.JButton();
        createMapButton = new javax.swing.JButton();
        deleteMapButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        gotoMapButton.setText("Go to map");
        gotoMapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoMapButtonActionPerformed(evt);
            }
        });

        createMapButton.setText("Create map");
        createMapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMapButtonActionPerformed(evt);
            }
        });

        deleteMapButton.setText("Delete map");
        deleteMapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMapButtonActionPerformed(evt);
            }
        });

        statusLabel.setText("Welcome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addComponent(statusLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gotoMapButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createMapButton)
                        .addGap(191, 191, 191)
                        .addComponent(deleteMapButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gotoMapButton)
                    .addComponent(createMapButton)
                    .addComponent(deleteMapButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gotoMapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoMapButtonActionPerformed
        if (jTable1.getSelectedRow() > -1) {
            Main.switch2mapview();
            String selected = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0);
            //Main.con.sendData((byte) 71, selected.getBytes());

        } else {
            tools.ModalMsg.display("Please select a map or create one.");
        }
}//GEN-LAST:event_gotoMapButtonActionPerformed

    private void deleteMapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMapButtonActionPerformed
        if (jTable1.getSelectedRow() > -1) {
            String selected = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0);
            //select map to delete and auth on it..
            //Main.con.sendData((byte) 71, selected.getBytes());
            if (new LoginPanel().createAndShowGUI()) {
                //Main.con.sendData((byte) 17, selected.getBytes());
                statusLabel.setText("Map deletion successfull.");
            } else {
                tools.ModalMsg.display("Map deletion failed.");
            }

        } else {
            tools.ModalMsg.display("No map selected.");
        }

    }//GEN-LAST:event_deleteMapButtonActionPerformed

    private void createMapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMapButtonActionPerformed
        OptionPaneMultiple opt = new OptionPaneMultiple(this);
        opt.newMap();
        if (opt.completed()) {
            //Main.con.sendData((byte) 25, tools.ByteArrayUtils.getSerializedBytes(new message.newMapData(opt.get3Input()[0], opt.get3Input()[1], opt.get3Input()[2], opt.getPassword())));
            statusLabel.setText("Map created successfully.");
        }
    }//GEN-LAST:event_createMapButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton createMapButton;
    public javax.swing.JButton deleteMapButton;
    public javax.swing.JButton gotoMapButton;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    public javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
