/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * NewNode.java
 *
 * Created on 31 Δεκ 2010, 1:52:12 μμ
 */
package jnodes3clientse;

import dataGenerator.snmpGetIfList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import mapElements.Node;
import mapElements.NodeInterface;

/**
 *
 * @author tsol
 */
public class NodeInfo extends javax.swing.JPanel {

    private final DefaultListModel<String> ifModel = new DefaultListModel<>();
    private NodeInterface[] iflist = {};
    Node theNode = null;

    public NodeInfo(Node node) {
        theNode = node;
        initComponents();
        ifList.setModel(ifModel);
        if (ifList == null) {
            ifList = new javax.swing.JList<>();
            jScrollPane1.setViewportView(ifList);
        }
        if (!(ifList.getModel() instanceof DefaultListModel)) {
            ifList.setModel(new DefaultListModel<String>());
        }
        populateList(node);

    }

    private void populateList(Node node) {
        ifModel.clear();
        ipField.setText(node.getIp());
        nameField.setText(node.getNodeName());
        iflist = node.getIfList();
        if (iflist != null) {
            for (NodeInterface iflist1 : iflist) {
                ifModel.addElement(iflist1.getLabel());
            }
        } else {
            ifModel.addElement("(interface scan pending)");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ipField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ifList = new javax.swing.JList<>();

        ipField.setEditable(false);
        ipField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipFieldActionPerformed(evt);
            }
        });

        nameField.setEditable(false);

        jLabel1.setText("Name:");

        jLabel3.setText("Ip address:");

        jButton1.setText("SNMP query now");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ifList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ifList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Interfaces", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameField)
                            .addComponent(ipField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ipFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (theNode.getIp() != null && !theNode.getIp().isEmpty()
                && theNode.getSnmpv3username() != null && !theNode.getSnmpv3username().isEmpty()
                && theNode.getSnmpv3auth() != null && !theNode.getSnmpv3auth().isEmpty()
                && theNode.getSnmpv3priv() != null && !theNode.getSnmpv3priv().isEmpty()) {
            System.out.println("[SNMP INFO:] checking interfaces of node " + theNode.getNodeName() + " - " + theNode.getID());
            snmpGetIfList snmplist = new snmpGetIfList(theNode.getIp(), theNode.getSnmpv3username(), theNode.getSnmpv3auth(), theNode.getSnmpv3priv(), theNode.getSnmpv3encr());

            String[] tmp = snmplist.getList();
            NodeInterface[] nodeIfList = new NodeInterface[tmp.length];
            String[] index = snmplist.getIndex();
            for (int j = 0; j < tmp.length; j++) {
                //System.out.print(index[j]);
                //System.out.println(" " + tmp[j]);
                nodeIfList[j] = new NodeInterface(tmp[j], tmp[j] + "(" + index[j] + ")", index[j]);
            }
            theNode.setIfList(nodeIfList);
            populateList(theNode);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ifList;
    private javax.swing.JTextField ipField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameField;
    // End of variables declaration//GEN-END:variables
}
